import Head from 'next/head'
import Layout from '../components/Layout'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>

      <h2>Music forum</h2>
      </Layout>

     
    </div>
  )
}
